#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: f35655a
#
Name     : R-pcaPP
Version  : 2.0.4.1
Release  : 54
URL      : https://cran.r-project.org/src/contrib/pcaPP_2.0-4-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pcaPP_2.0-4-1.tar.gz
Summary  : Robust PCA by Projection Pursuit
Group    : Development/Tools
License  : GPL-3.0
Requires: R-pcaPP-lib = %{version}-%{release}
Requires: R-mvtnorm
BuildRequires : R-mvtnorm
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# `pcaPP`: Robust PCA by Projection Pursuit
<!-- badges: start -->
[![CRAN
version](https://www.r-pkg.org/badges/version/pcaPP)](https://cran.r-project.org/package=pcaPP)
[![R-CMD-check](https://github.com/valentint/pcaPP/workflows/R-CMD-check/badge.svg)](https://github.com/valentint/pcaPP/actions)
[![downloads](https://cranlogs.r-pkg.org/badges/pcaPP)](https://cran.r-project.org/package=pcaPP)
[![downloads](https://cranlogs.r-pkg.org/badges/grand-total/pcaPP)](https://cran.r-project.org/package=pcaPP)
[![license](https://img.shields.io/badge/license-GPL--3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0.en.html)
<!-- badges: end -->

%package lib
Summary: lib components for the R-pcaPP package.
Group: Libraries

%description lib
lib components for the R-pcaPP package.


%prep
%setup -q -n pcaPP
pushd ..
cp -a pcaPP buildavx2
popd
pushd ..
cp -a pcaPP buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723211995

%install
export SOURCE_DATE_EPOCH=1723211995
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pcaPP/DESCRIPTION
/usr/lib64/R/library/pcaPP/INDEX
/usr/lib64/R/library/pcaPP/Meta/Rd.rds
/usr/lib64/R/library/pcaPP/Meta/features.rds
/usr/lib64/R/library/pcaPP/Meta/hsearch.rds
/usr/lib64/R/library/pcaPP/Meta/links.rds
/usr/lib64/R/library/pcaPP/Meta/nsInfo.rds
/usr/lib64/R/library/pcaPP/Meta/package.rds
/usr/lib64/R/library/pcaPP/Meta/vignette.rds
/usr/lib64/R/library/pcaPP/NAMESPACE
/usr/lib64/R/library/pcaPP/R/pcaPP
/usr/lib64/R/library/pcaPP/R/pcaPP.rdb
/usr/lib64/R/library/pcaPP/R/pcaPP.rdx
/usr/lib64/R/library/pcaPP/doc/index.html
/usr/lib64/R/library/pcaPP/doc/matlab.R
/usr/lib64/R/library/pcaPP/doc/matlab.pdf
/usr/lib64/R/library/pcaPP/doc/matlab.rnw
/usr/lib64/R/library/pcaPP/help/AnIndex
/usr/lib64/R/library/pcaPP/help/aliases.rds
/usr/lib64/R/library/pcaPP/help/paths.rds
/usr/lib64/R/library/pcaPP/help/pcaPP.rdb
/usr/lib64/R/library/pcaPP/help/pcaPP.rdx
/usr/lib64/R/library/pcaPP/html/00Index.html
/usr/lib64/R/library/pcaPP/html/R.css
/usr/lib64/R/library/pcaPP/tests/tpcapp.R
/usr/lib64/R/library/pcaPP/tests/tpcapp.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/pcaPP/libs/pcaPP.so
/V4/usr/lib64/R/library/pcaPP/libs/pcaPP.so
/usr/lib64/R/library/pcaPP/libs/pcaPP.so
